colormod.settings:
  type: config_object
  label: "ColorMod settings"
  mapping:
    colormod:
      type: mapping
      mapping:
        page_title:
          type: text
          label: "ColorMod generator page title:"
        source_text:
          type: text
          label: "Source text for ColorMod generation:"
